In [5]:
from sklearn.decomposition import PCA
import pandas as pd
data = [[7,4,3],
             [4,1,8],
             [6,3,5],
             [8,6,1],
             [8,5,7],
             [7,2,9],
             [5,3,3],
             [9,5,8],
             [7,4,5],
             [8,2,2]]
pca = PCA(n_components = 3)

#Create the transformation matrix of the data. It is the rotational matrix
pcaTransform = pca.fit(data)

#Transform the data on rotational matrix
rotatedData = pcaTransform.transform(data)

#Create the new dataframe with two variables
data_PCA = pd.DataFrame(data = rotatedData, columns = ['PCA1', 'PCA2', 'PCA3'])
data_PCA

[[ 2.15142276 -0.17311941 -0.10681648]
 [-3.80418259 -2.88749898 -0.5104355 ]
 [-0.15321328 -0.98688598 -0.26941001]
 [ 4.7065185   1.30153634 -0.65167999]
 [-1.29375788  2.27912632 -0.44919235]
 [-4.0993133   0.1435814   0.80312818]
 [ 1.62582148 -2.23208282 -0.80281431]
 [-2.11448986  3.2512433   0.16837351]
 [ 0.2348172   0.37304031 -0.27513962]
 [ 2.74637697 -1.06894049  2.09398657]]


PCA1      PCA2      PCA3
0  2.151423 -0.173119 -0.106816
1 -3.804183 -2.887499 -0.510436
2 -0.153213 -0.986886 -0.269410
3  4.706518  1.301536 -0.651680
4 -1.293758  2.279126 -0.449192
5 -4.099313  0.143581  0.803128
6  1.625821 -2.232083 -0.802814
7 -2.114490  3.251243  0.168374
8  0.234817  0.373040 -0.275140
9  2.746377 -1.068940  2.093987

In [10]:
import numpy as np
X = np.array(data)
centered_matrix = X - X.mean(axis=1)[:, np.newaxis]
cov = np.dot(centered_matrix, centered_matrix.T)
eigvals, eigvecs = np.linalg.eig(cov)
print(eigvals)
print(eigvecs)

[ 0.00000000e+00+0.00000000e+00j  6.36214904e+01+0.00000000e+00j
  7.10451762e+01+0.00000000e+00j -2.51438977e-15+9.53555155e-16j
 -2.51438977e-15-9.53555155e-16j -2.89076177e-15+0.00000000e+00j
 -4.28023914e-16+7.46491714e-16j -4.28023914e-16-7.46491714e-16j
  2.45856618e-16+0.00000000e+00j  1.69529840e-30+0.00000000e+00j]
[[-0.93015684+0.j         -0.35027092+0.j         -0.11008426+0.j
   0.12727318-0.19311212j  0.12727318+0.19311212j -0.09462802+0.j
  -0.36644332-0.17422045j -0.36644332+0.17422045j -0.8469462 +0.j
   0.93015684+0.j        ]
 [-0.0707211 +0.j          0.00261761+0.j          0.58922898+0.j
   0.2770772 -0.16193721j  0.2770772 +0.16193721j -0.55899025+0.j
   0.25639775-0.19716926j  0.25639775+0.19716926j  0.00160238+0.j
   0.0707211 +0.j        ]
 [ 0.06406126+0.j         -0.21793772+0.j          0.1521582 +0.j
   0.22013813-0.2623753j   0.22013813+0.2623753j  -0.26540732+0.j
   0.0761142 -0.02427632j  0.0761142 +0.02427632j  0.07999197+0.j
  -0.06406126+0.j        ]